create extension if not exists vector with schema extensions;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  target_exam_year integer not null default 2028,
  timezone text not null default 'Asia/Shanghai',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 160),
  subject text not null check (subject in ('math','english','politics','cs408','career')),
  plan_level text not null default 'day' check (plan_level in ('stage','week','day')),
  planned_minutes integer not null default 30 check (planned_minutes between 1 and 1440),
  due_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id uuid references public.tasks(id) on delete set null,
  subject text not null check (subject in ('math','english','politics','cs408','career')),
  started_at timestamptz not null,
  ended_at timestamptz not null,
  paused_seconds integer not null default 0 check (paused_seconds >= 0),
  source text not null default 'timer' check (source in ('timer','manual')),
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ended_at > started_at)
);

create index study_sessions_user_started_idx on public.study_sessions(user_id, started_at);
create index tasks_user_due_idx on public.tasks(user_id, due_at);

create table public.mistake_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (subject in ('math','english','politics','cs408')),
  title text not null,
  question text not null,
  answer text not null default '',
  error_reason text not null default '',
  mastery integer not null default 1 check (mastery between 1 and 5),
  next_review_at timestamptz,
  review_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.school_options (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  tier text not null check (tier in ('stretch','match','safety')),
  university text not null,
  college text not null,
  major_code text not null,
  major_name text not null,
  degree_type text not null check (degree_type in ('academic','professional')),
  exam_year integer not null,
  exam_subjects jsonb not null default '[]'::jsonb,
  tuition_total integer,
  duration_years numeric(3,1),
  location text,
  source_url text not null,
  source_checked_at timestamptz not null default now(),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, college, major_code, exam_year)
);

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source_type text not null check (source_type in ('upload','web')),
  title text not null,
  original_filename text,
  source_url text,
  storage_path text,
  content_type text not null,
  byte_size bigint,
  sha256 text,
  version integer not null default 1,
  ingestion_status text not null default 'queued' check (ingestion_status in ('queued','processing','ready','failed')),
  ingestion_error text,
  downloaded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index documents_user_hash_idx on public.documents(user_id, sha256) where sha256 is not null;
create unique index documents_user_url_idx on public.documents(user_id, source_url) where source_url is not null;

create table public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  chunk_index integer not null,
  heading text,
  page_number integer,
  locator text not null,
  content text not null,
  content_tsv tsvector generated always as (to_tsvector('simple', content)) stored,
  embedding extensions.vector(1536),
  created_at timestamptz not null default now(),
  unique(document_id, chunk_index)
);

create index document_chunks_fts_idx on public.document_chunks using gin(content_tsv);
create index document_chunks_embedding_idx on public.document_chunks using hnsw (embedding extensions.vector_cosine_ops);

create table public.import_proposals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source_url text not null,
  title text not null,
  summary text not null default '',
  content_type text,
  estimated_bytes bigint,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.agent_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('coach','tutor','combined')),
  title text not null default '新对话',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.action_proposals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  thread_id uuid references public.agent_threads(id) on delete set null,
  agent text not null check (agent in ('coach','tutor')),
  action text not null,
  payload jsonb not null,
  summary text not null,
  idempotency_key text not null,
  status text not null default 'pending' check (status in ('pending','approved','edited','rejected','applied','failed')),
  decided_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, idempotency_key)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  proposal_id uuid references public.action_proposals(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace view public.daily_study_contributions
with (security_invoker = true) as
select
  user_id,
  (started_at at time zone 'Asia/Shanghai')::date as study_date,
  subject,
  floor(sum(greatest(0, extract(epoch from (ended_at - started_at)) - paused_seconds)) / 60)::integer as effective_minutes,
  count(*)::integer as session_count
from public.study_sessions
group by user_id, (started_at at time zone 'Asia/Shanghai')::date, subject;

create or replace function public.match_document_chunks(
  query_embedding extensions.vector(1536),
  match_count integer default 8,
  filter_document_ids uuid[] default null
)
returns table (
  id bigint,
  document_id uuid,
  title text,
  locator text,
  content text,
  similarity float
)
language sql stable security invoker
as $$
  select
    dc.id,
    dc.document_id,
    d.title,
    dc.locator,
    dc.content,
    1 - (dc.embedding <=> query_embedding) as similarity
  from public.document_chunks dc
  join public.documents d on d.id = dc.document_id
  where dc.user_id = auth.uid()
    and (filter_document_ids is null or dc.document_id = any(filter_document_ids))
    and dc.embedding is not null
  order by dc.embedding <=> query_embedding
  limit least(match_count, 30);
$$;

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.study_sessions enable row level security;
alter table public.mistake_cards enable row level security;
alter table public.school_options enable row level security;
alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;
alter table public.import_proposals enable row level security;
alter table public.agent_threads enable row level security;
alter table public.action_proposals enable row level security;
alter table public.audit_logs enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'tasks','study_sessions','mistake_cards','school_options','documents',
    'document_chunks','import_proposals','agent_threads','action_proposals','audit_logs'
  ] loop
    execute format(
      'create policy %I on public.%I for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())',
      table_name || '_owner_policy', table_name
    );
  end loop;
end $$;

-- profiles use their primary key as the owner key.
create policy profiles_owner_policy on public.profiles
for all to authenticated using (id = auth.uid()) with check (id = auth.uid());
